version: 1.0.{build}
image: Visual Studio 2017

environment:
  API_KEY_SECRET:
    secure: pHwfrpT3WI+xkvHkGHjzqg2WwmGz+Qx4oN3L/o4iPq+N84EdJOT74bq9j60NMrFs

skip_branch_with_pr: true
branches:
  only:
  - master

build_script:
  - dotnet build NetGrpcSentry.sln --configuration Release

test_script:
  - dotnet test NetGrpcSentryTest/NetGrpcSentryTest.csproj

deploy_script:
  - ps: |
      dotnet pack NetGrpcSentry/NetGrpcSentry.csproj -c Release -Symbols -SymbolPackageFormat snupkg /p:PackageVersion=$env:APPVEYOR_REPO_TAG_NAME
      dotnet nuget push NetGrpcSentry/bin/Release/NetGrpcSentry.$env:APPVEYOR_REPO_TAG_NAME.nupkg -k $env:API_KEY_SECRET -s https://www.nuget.org
